import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service | Color Palette Generator',
  description: 'Terms of service for Color Palette Generator.',
};

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
      <h1 className="text-3xl font-bold text-slate-900 mb-8">Terms of Service</h1>

      <div className="prose prose-slate max-w-none space-y-6 text-slate-600">
        <p>Last updated: {new Date().toLocaleDateString()}</p>

        <p>Welcome to Color Palette Generator. By using our tool, you agree to these simple terms of service.</p>

        <h2 className="text-xl font-semibold text-slate-900 mt-8 mb-4">1. General Use</h2>
        <p>This tool is provided for general creative, design, and educational use. It is provided &quot;as is&quot; without any warranties.</p>

        <h2 className="text-xl font-semibold text-slate-900 mt-8 mb-4">2. Intellectual Property</h2>
        <p>The color palettes generated by this tool are mathematical combinations of color values. We do not claim exclusive intellectual property rights over any palette generated here. Generated colors are not guaranteed to be unique to you.</p>

        <h2 className="text-xl font-semibold text-slate-900 mt-8 mb-4">3. Suitability and Legal Use</h2>
        <p>There is no guarantee that generated palettes are suitable for every brand, specific accessibility requirement, or legal use case. Some combinations of colors may already be trademarked by other companies in specific industries (e.g., T-Mobile&apos;s magenta).</p>

        <h2 className="text-xl font-semibold text-slate-900 mt-8 mb-4">4. Accessibility Guidance</h2>
        <p>The accessibility labels (e.g., &quot;Good for text&quot;, contrast ratios) provided by the tool are simplified mathematical guidelines based on WCAG formulas. They are a helpful starting point, not a full accessibility audit. Users are entirely responsible for testing colors in their own actual contexts and layouts.</p>

        <h2 className="text-xl font-semibold text-slate-900 mt-8 mb-4">5. Liability</h2>
        <p>We are not liable for any damages, legal issues, or losses that may arise from using color palettes generated by this tool in your projects.</p>
      </div>
    </div>
  );
}
